### PR TITLE
Minor typo in VM memory vitals

### PR DESCRIPTION
**Pull request by kjbhu**

### CODE REVIEW

**Comment by mlimonczenko** [comment]
Thank you for the PR, @kjbhu. Before I merge, I'm wondering why several of the lines were deleted. The commit message says a "minor typo".

**Comment by kjbhu** [comment]
Hi @mlimonczenko, 
I'm sorry that the commit message does not describe correctly the actual change. According to UaaMetricsEmitter there is only 5 VM vital metrics reported by UAA. The doc contained 6, two of which had the same text (vitals.vm.memory.total) but different links to values provided by JVM. The last entnry even contained a link that belongs to the next section (Java Virtual Machine Vitals). I presumed it's a minor copy-paste error, where some of the lines were only partially updated, so removed the extra entry and changed the remaing ones so that the description and the link to JVM matches.

**Comment by mlimonczenko** [comment]
Thank you for this explanation, @kjbhu. I'll go ahead and merge.

**Comment by kjbhu** [comment]
Cool, thanks.

**Pull request merged**
